# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Michael Bastos
tagline:          'Online Writings and Resume'
description:      'Self & University taught Engineer, Data Scientist & Former Marine working as an Engineering Manager in Austin, TX. Follow me on <a href="https://github.com/bastosmichael" target="_blank">Github</a> or <a href="https://www.linkedin.com/in/michaelbastos" target="_blank">LinkedIn</a>.'
url:              https://michaelbastos.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/bastosmichael

plugins:
  - jekyll-analytics
  - jekyll-sitemap
  - jekyll-paginate

include: ['_pages']

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-4772504-2        # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
